[package]
name = "elemeld"
version = "0.1.0"
authors = ["Kira Bruneau <kira.bruneau@gmail.com>"]

[dependencies]
mio = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
rustc-serialize = "*"
x11-dl = "*"
dylib = "*"
libc = "*"
nix = "*"
log = "*"
env_logger = "*"
docopt = "*"
docopt_macros = "*"
